[package]
name = "learn_autosurgeon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autosurgeon = "0.7"
automerge = "0.4"
